# Generated by Django 3.2.8 on 2021-10-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='allow_mailing',
            field=models.BooleanField(default=False),
        ),
    ]
